- import_tasks: "{{ role_path }}/tasks/init.yml"
  tags:
    - always

- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool and matrix_email2matrix_enabled|bool"
  tags:
    - setup-all
    - setup-email2matrix

- import_tasks: "{{ role_path }}/tasks/setup_email2matrix.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-email2matrix
