---

- name: Fail if no mappings
  fail:
    msg: >
      You need to define at least one mapping in `matrix_email2matrix_matrix_mappings` for enabling Email2Matrix.
  when: "matrix_email2matrix_matrix_mappings|length == 0"
