---

- import_tasks: "{{ role_path }}/tasks/ext/rest-auth/setup_install.yml"
  when: matrix_synapse_ext_password_provider_rest_auth_enabled|bool

- import_tasks: "{{ role_path }}/tasks/ext/rest-auth/setup_uninstall.yml"
  when: "not matrix_synapse_ext_password_provider_rest_auth_enabled|bool"
